
-- this file is generated by tangling H99.org in emacs. do not modify manually.

module H99 (
    myReverse,
    isPalindrome
)
where

myReverse :: [a] -> [a]
myReverse l = myReverse' l []
myReverse' [] accu = accu
myReverse' (x:xs) accu = myReverse' xs (x:accu)

isPalindrome :: (Eq a) => [a] -> Bool
isPalindrome [] = True
isPalindrome l = if l == myReverse l 
                     then True 
                     else False
