
-- this file is generated by tangling H99.org in emacs. do not modify manually.

import H99

az = ['a'..'z']
l  = [1,2,3]
ll = [1..10]

testFunc ::(Show f) => String -> f -> IO () 
testFunc name f = do 
    putStrLn $ "Testing function " ++ name
    print f

main :: IO ()
main = do
    testFunc "myReverse" (myReverse l)
    testFunc "myReverse" (myReverse ll)
    testFunc "myReverse" (myReverse az)

    testFunc "isPalindrome" (isPalindrome  l)
    testFunc "isPalindrome" (isPalindrome  p1)
    testFunc "isPalindrome" (isPalindrome  p2)

-- test data for P6, palindrome
p1 = "madamimadam"
p2 = [1,2,4,8,16,8,4,2,1]
